<?php

$extensionPath = t3lib_extMgm::extPath('party');

return array(
	'tx_party_api' => $extensionPath . 'api/class.tx_party_api.php',
	'tx_party_div' => $extensionPath . 'div/class.tx_party_div.php',
	'tx_party_labels' => $extensionPath . 'hooks/class.tx_party_labels.php',
	'tx_party_staticinfotables' => $extensionPath . 'hooks/class.tx_party_staticinfotables.php',
	'JambageCom\\Party\\Model\\AbstractObject' => $extensionPath . 'Classes/Model/AbstractObject.php',
	'JambageCom\\Party\\Model\\Account' => $extensionPath . 'Classes/Model/Account.php',
	'JambageCom\\Party\\Model\\Address' => $extensionPath . 'Classes/Model/Address.php',
	'JambageCom\\Party\\Model\\AddressUsage' => $extensionPath . 'Classes/Model/AddressUsage.php',
	'JambageCom\\Party\\Model\\Allergy' => $extensionPath . 'Classes/Model/Allergy.php',
	'JambageCom\\Party\\Model\\BirthSign' => $extensionPath . 'Classes/Model/BirthSign.php',
	'JambageCom\\Party\\Model\\Contact' => $extensionPath . 'Classes/Model/Contact.php',
	'JambageCom\\Party\\Model\\ContactNumber' => $extensionPath . 'Classes/Model/ContactNumber.php',
	'JambageCom\\Party\\Model\\ContactNumberUsage' => $extensionPath . 'Classes/Model/ContactNumberUsage.php',
	'JambageCom\\Party\\Model\\CountryOfResidence' => $extensionPath . 'Classes/Model/CountryOfResidence.php',
	'JambageCom\\Party\\Model\\Disability' => $extensionPath . 'Classes/Model/Disability.php',
	'JambageCom\\Party\\Model\\Document' => $extensionPath . 'Classes/Model/Document.php',
	'JambageCom\\Party\\Model\\ElectronicAddressIdentifier' => $extensionPath . 'Classes/Model/ElectronicAddressIdentifier.php',
	'JambageCom\\Party\\Model\\ElectronicAddressIdentifierUsage' => $extensionPath . 'Classes/Model/ElectronicAddressIdentifierUsage.php',
	'JambageCom\\Party\\Model\\Ethnicity' => $extensionPath . 'Classes/Model/Ethnicity.php',
	'JambageCom\\Party\\Model\\Event' => $extensionPath . 'Classes/Model/Event.php',
	'JambageCom\\Party\\Model\\Favourite' => $extensionPath . 'Classes/Model/Favourite.php',
	'JambageCom\\Party\\Model\\Habit' => $extensionPath . 'Classes/Model/Habit.php',
	'JambageCom\\Party\\Model\\Hobby' => $extensionPath . 'Classes/Model/Hobby.php',
	'JambageCom\\Party\\Model\\Identifier' => $extensionPath . 'Classes/Model/Identifier.php',
	'JambageCom\\Party\\Model\\Image' => $extensionPath . 'Classes/Model/Image.php',
	'JambageCom\\Party\\Model\\Language' => $extensionPath . 'Classes/Model/Language.php',
	'JambageCom\\Party\\Model\\Language' => $extensionPath . 'Classes/Model/Language.php',
	'JambageCom\\Party\\Model\\Mark' => $extensionPath . 'Classes/Model/Mark.php',
	'JambageCom\\Party\\Model\\Membership' => $extensionPath . 'Classes/Model/Membership.php',
	'JambageCom\\Party\\Model\\Name' => $extensionPath . 'Classes/Model/Name.php',
	'JambageCom\\Party\\Model\\Nationality' => $extensionPath . 'Classes/Model/Nationality.php',
	'JambageCom\\Party\\Model\\Occupation' => $extensionPath . 'Classes/Model/Occupation.php',
	'JambageCom\\Party\\Model\\OccupationRank' => $extensionPath . 'Classes/Model/OccupationRank.php',
	'JambageCom\\Party\\Model\\OccupationRole' => $extensionPath . 'Classes/Model/OccupationRole.php',
	'JambageCom\\Party\\Model\\OrganisationNature' => $extensionPath . 'Classes/Model/OrganisationNature.php',
	'JambageCom\\Party\\Model\\Party' => $extensionPath . 'Classes/Model/Party.php',
	'JambageCom\\Party\\Model\\PersonNameTitle' => $extensionPath . 'Classes/Model/PersonNameTitle.php',
	'JambageCom\\Party\\Model\\PhysicalStatus' => $extensionPath . 'Classes/Model/PhysicalStatus.php',
	'JambageCom\\Party\\Model\\Preference' => $extensionPath . 'Classes/Model/Preference.php',
	'JambageCom\\Party\\Model\\Qualification' => $extensionPath . 'Classes/Model/Qualification.php',
	'JambageCom\\Party\\Model\\QualificationStatus' => $extensionPath . 'Classes/Model/QualificationStatus.php',
	'JambageCom\\Party\\Model\\Relationship' => $extensionPath . 'Classes/Model/Relationship.php',
	'JambageCom\\Party\\Model\\RelationshipType' => $extensionPath . 'Classes/Model/RelationshipType.php',
	'JambageCom\\Party\\Model\\Religion' => $extensionPath . 'Classes/Model/Religion.php',
	'JambageCom\\Party\\Model\\Revenue' => $extensionPath . 'Classes/Model/Helper/Revenue.php',
	'JambageCom\\Party\\Model\\Foreign\\StaticCountry' => $extensionPath . 'Classes/Model/Static/Country.php',
	'JambageCom\\Party\\Model\\Foreign\\StaticCountryZone' => $extensionPath . 'Classes/Model/Foreign/StaticCountryZone.php',
	'JambageCom\\Party\\Model\\Foreign\\StaticCurrency' => $extensionPath . 'Classes/Model/Foreign/StaticCurrency.php',
	'JambageCom\\Party\\Model\\Foreign\\StaticLanguage' => $extensionPath . 'Classes/Model/Foreign/StaticLanguage.php',
	'JambageCom\\Party\\Model\\Foreign\\StaticMarket' => $extensionPath . 'Classes/Model/Foreign/StaticMarket.php',
	'JambageCom\\Party\\Model\\StockMarket' => $extensionPath . 'Classes/Model/StockMarket.php',
	'JambageCom\\Party\\Model\\Type' => $extensionPath . 'Classes/Model/Type.php',
	'JambageCom\\Party\\Model\\Usage' => $extensionPath . 'Classes/Model/Usage.php',
	'JambageCom\\Party\\Model\\Vehicle' => $extensionPath . 'Classes/Model/Vehicle.php',
	'JambageCom\\Party\\Model\\VehicleManufacturer' => $extensionPath . 'Classes/Model/VehicleManufacturer.php',
	'JambageCom\\Party\\Model\\Visa' => $extensionPath . 'Classes/Model/Visa.php',
);
?>