<?php
if (!defined ('TYPO3_MODE')) 	die ('Access denied.');

// Activate Hooks in TCE-Main for the hotlist updates of static_info_tables
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass'][] = 'EXT:party/hooks/class.tx_party_staticinfotables.php:tx_party_staticinfotables';


t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_birth_signs=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_birth_stars=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_ethnicities=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_habits=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_hobbies=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_occupation_ranks=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_occupation_roles=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_organisation_natures=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_person_name_titles=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_physical_status=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_qualification_status=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_religions=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_types=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_vehicle_manufacturer=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_accounts=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_addresses=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_contacts=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_contact_numbers=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_countries_of_residence=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_disabilities=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_documents=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_eletronic_address_identifiers=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_images=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_languages=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_marks=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_nationalities=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_occupations=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_names=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_qualifications=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_revenues=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_stock_markets=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_vehicles=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_visas=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_parties=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_events=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_identifiers=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_memberships=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_allergies=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_favourites=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_preferences=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_usages=1
');
t3lib_extMgm::addUserTSConfig('
	options.saveDocNew.tx_party_relationships=1
');
?>